FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY app app
COPY tests tests
COPY test.sh test.sh

COPY . .

RUN chmod +x test.sh

CMD ["sh", "test.sh"]

